[2025-08-19T04:58:03.317+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-08-19T04:58:03.339+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: consumer_dag.read_file_task manual__2025-08-19T04:58:01.340895+00:00 [queued]>
[2025-08-19T04:58:03.347+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: consumer_dag.read_file_task manual__2025-08-19T04:58:01.340895+00:00 [queued]>
[2025-08-19T04:58:03.348+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-08-19T04:58:03.362+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): read_file_task> on 2025-08-19 04:58:01.340895+00:00
[2025-08-19T04:58:03.369+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=85) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-08-19T04:58:03.371+0000] {standard_task_runner.py:63} INFO - Started process 87 to run task
[2025-08-19T04:58:03.371+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'consumer_dag', 'read_file_task', 'manual__2025-08-19T04:58:01.340895+00:00', '--job-id', '13', '--raw', '--subdir', 'DAGS_FOLDER/consumer_dag.py', '--cfg-path', '/tmp/tmps2ls81yz']
[2025-08-19T04:58:03.374+0000] {standard_task_runner.py:91} INFO - Job 13: Subtask read_file_task
[2025-08-19T04:58:03.421+0000] {task_command.py:426} INFO - Running <TaskInstance: consumer_dag.read_file_task manual__2025-08-19T04:58:01.340895+00:00 [running]> on host 6cacbbe28f9c
[2025-08-19T04:58:03.537+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='consumer_dag' AIRFLOW_CTX_TASK_ID='read_file_task' AIRFLOW_CTX_EXECUTION_DATE='2025-08-19T04:58:01.340895+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-19T04:58:01.340895+00:00'
[2025-08-19T04:58:03.540+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-08-19T04:58:03.541+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-08-19T04:58:03.541+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/consumer_dag.py", line 13, in read_file
    raise FileNotFoundError("File not found. Please run Producer DAG first.")
FileNotFoundError: File not found. Please run Producer DAG first.
[2025-08-19T04:58:03.554+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=consumer_dag, task_id=read_file_task, run_id=manual__2025-08-19T04:58:01.340895+00:00, execution_date=20250819T045801, start_date=20250819T045803, end_date=20250819T045803
[2025-08-19T04:58:03.609+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 13 for task read_file_task (File not found. Please run Producer DAG first.; 87)
[2025-08-19T04:58:03.628+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-08-19T04:58:03.648+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-08-19T04:58:03.652+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
